### ISSUE TITLE
Authentication endpoint issue

### ISSUE THREAD

**Issue by GregMHalo** [homotechsual/HaloAPI#1]
When using a separate authentication URL in Halo, the endpoint may not end in /Auth. It may just be the domain/root address, but Connect-HaloAPI seems to always append /Auth. This presents a problem for triallists using the https://uk-trial.halopsa.com auth endpoint. It sends the request to https://uk-trial.halopsa.com/auth/token?tenant=Tenant123 rather than https://uk-trial.halopsa.com/token?tenant=Tenant123 as it should, unless I'm doing something wrong.

**Comment by homotechsual** [comment]
Oh that's a nuance I wasn't aware of - how would you suggest handling it?

**Comment by homotechsual** [comment]
Is there a way we can easily detect what pattern they will have?

**Comment by GregMHalo** [comment]
I think it would be best to allow an optional -AuthURL parameter in Connect-HaloAPI as there's not necessarily any pattern to it.

**Comment by homotechsual** [comment]
> I think it would be best to allow an optional -AuthURL parameter in Connect-HaloAPI as there's not necessarily any pattern to it.

I'll push a preview release shortly with a fix for this. I've added an `-AuthPath` parameter for this - since we use the `-URL` as a base URL already. 

So if you do `Connect-HaloAPI -URL 'https://testing.halopsa.com' -AuthPath 'custom/auth/token' @OtherParams` it'll use your auth path rather than the 'standard' auth route.

**Comment by homotechsual** [comment]
Released `Install-Module -Name HaloAPI -AllowPrerelease`

**Comment by GregMHalo** [comment]
Thanks! Would the `-AuthPath` be a URI? I.E. `-AuthPath 'uk-trial.halopsa.com/token'`.

To clarify, it does always take the form [AuthURI]/token so it could just be `-AuthPath 'uk-trial.halopsa.com'` and you could add the '/token' on where necessary.

**Comment by homotechsual** [comment]
`-AuthPath` is everything after the URL upto/including Token. It essentially disables handling of the auth path by the module and assumes that you've given it the complete path to the endpoint.

So if you had `https://uk-trial.halopsa.com` and the auth was at `https://uk-trial.halopsa.com/token` you'd use:

`Connect-HaloAPI -URL 'https://uk-trial.halopsa.com' -AuthPath 'token'`

**Comment by homotechsual** [comment]
The auth path is being built here:

https://github.com/homotechsual/HaloAPI/blob/b5e29cc717cd1740c2d00976fea580c7f6b2d7d0/Public/Connect-HaloAPI.ps1#L67

**Comment by GregMHalo** [comment]
If I'm understanding correctly then this will still be a problem because the auth URL can be entirely different to the base URL. For example, trial customers are currently given a base URL of `https://cutomer123.halopsa.com` and an auth URL of `https://uk-trial.halopsa.com/` (all trials share the same auth URL). In fact, the AuthPath can only be non-standard (and by non-standard, I just mean it would exclude the `/Auth` part) if the auth URL is different to the base URL. Sorry if I didn't make that clear.

Hence the suggestion of an optional `-AuthURL` parameter that would be given as a full URL.

**Comment by homotechsual** [comment]
Ah - okay I misunderstood that entirely - reworking the beta now!

**Comment by homotechsual** [comment]
Beta3 should handle this now with `-AuthURL` it'll accept with or without a path part - without - it'll add `/auth/token` with - it'll use verbatim.

**Comment by lwhitelock** [comment]
@GregMHalo Would it be better for us to hit /api/instanceinfo and then grab the auth_url from that?

**Comment by GregMHalo** [comment]
@lwhitelock Actually, yes, that would be a better solution. Or you can use /api/authinfo.

**Comment by homotechsual** [comment]
Released Beta4 which takes this route now :-) No more `-AuthURL` just autodetection and fallback to `-URL` + `/auth/token`

**Comment by homotechsual** [comment]
Did you have chance to test against Beta4 @GregMHalo? :-)

**Comment by GregMHalo** [comment]
Hi, just tested the prerelease and I'm still still getting a 500 error as before, with no error in our auth logs, which suggests to me that it's not reaching the proper auth endpoint. If you want to create a trial from our website, you should be able to reproduce it with that.

**Comment by homotechsual** [comment]
Perfect - thanks Greg. Resolved it - will push a beta5 release now. Can you have someone remove the trial `homotechsual.halopsa.com` :-)

**Comment by homotechsual** [comment]
Beta 5 is up, if you wouldn't mind testing.

**Comment by GregMHalo** [comment]
Yep, that works. Thanks!
