### ISSUE TITLE
[bug] Get-HaloCustomField not working

### ISSUE THREAD

**Issue by FarazUSL** [homotechsual/HaloAPI#15]
Hello,
Is there a bug with with "Get-HaloCustomField"
Trying to use that results in  "Get-HaloCustomField: The term 'Get-HaloCustomField' is not recognized as a name of a cmdlet, function, script file, or executable program"

This is the version running and other command tried so far seem to be working
Get-Module HaloAPI
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     1.10.1                HaloAPI                             {Connect-HaloAPI, Get-HaloAction, Get-HaloAgent, …
Thanks

**Comment by homotechsual** [comment]
It works fine here - can you update to `1.11.1`

**Comment by FarazUSL** [comment]
The latest I see is 1.10.1.
I tried setting the recquired version but that didn't do anything :(

PS C:\Windows\System32> Update-Module HaloApi -RequiredVersion 1.11.1
PS C:\Windows\System32> Get-Module HaloAPI

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     1.10.1                HaloAPI                             {Connect-HaloAPI, Get-HaloAction, Get-HaloAgent, …

**Comment by homotechsual** [comment]
Can you try `Uninstall-Module HaloAPI` and `Install-Module -Name HaloAPI`

**Comment by FarazUSL** [comment]
HaHa Thanks for the quick help...Uninstall\Reinstall worked to get the newer version of the module...wonder why Update-Module wasn't grabbing the latest version.
And I can now use "Get-HaloCustomField" :)
FYI - https://github.com/homotechsual/HaloAPI/releases still shows 1.10.1 as the latest

**Comment by homotechsual** [comment]
Thanks, published the release on GH :-D
