### ISSUE TITLE
On-Premises Support?

### ISSUE THREAD

**Issue by ebarley946** [homotechsual/HaloAPI#19]
New-HaloError: C:\Program Files\WindowsPowerShell\Modules\haloapi\1.11.1\Public\Connect-HaloAPI.ps1:154

Line |

154 | New-HaloError $_ -HasResponse

| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

| The Halo API said invalid_client. The API returned the following HTTP error response: 401 Unauthorized

**Comment by homotechsual** [comment]
> The Halo API said invalid_client

Your API application is not setup correctly or you've used an incorrect client_id.

**Comment by ebarley946** [comment]
Thank you. I created the API connection again and noticed that the Client ID changed before I saved it.

**Comment by homotechsual** [comment]
Can this be closed then?

**Comment by ebarley946** [comment]
Yes thank you

***@***.***
Eric​    Barley

Coordinator
Corporate IT Systems Administrator II


Morton Community Bank
671 West Jackson Street
Morton  ,       IL        61550



Office: (309) 284‑1336
Fax: (309) 266‑8242
