### ISSUE TITLE
How to:

### ISSUE THREAD

**Issue by DirectITServicesUK** [homotechsual/HaloAPI#20]
Not really an issue, but how do you use some of these? For EG, New-HaloAgentBatch

**Comment by homotechsual** [comment]
Better documentation is coming - no fixed timeline but it's in progress!

The `*-*Batch` commandlets just run their standard commandlet in parallel.

e.g. `New-HaloAgentBatch` is just `New-HaloAgent` with parallel processing support to handle massive requests easier.

Both take a single parameter `-Agents` which is an array of agent objects.

```ps
$Agents = @(
  @{
    Name = 'Patricia Jones'
    FirstName = 'Patricia'
    Surname = 'Jones'
    Teams = @(@{ team_name = '2nd Line Support' })
    Departments = @( @{ department_id = 3 })
    Email = 'patricia@test.example'
    JobTitle = 'Senior Support Engineer'
  },
  @{
    Name = 'Mary Johnson'
    FirstName = 'Mary'
    Surname = 'Johnson'
    Teams = @(@{ team_name = 'Project Managers' })
    Departments = @( @{ department_id = 9 })
    Email = 'mary@test.example'
    JobTitle = 'Project Manager'
  },
)
```

**Comment by DirectITServicesUK** [comment]
Ahhhh. I see. Thanks for that

________________________________

DOUG HALL
MANAGING DIRECTOR
Direct IT Services Ltd
Mills House, Boscombe Down Business Park
Amesbury
SP4 7RX
Tel: 01980 348271
Mobile: 07597 194452
Email: ***@***.***
Web: directitservices.co.uk
IT Support portal - https://support.itportal.uk
 Direct IT Services Ltd accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company.
 
 Direct IT Services Ltd is a company registered in England and Wales under number 13656277.
 Registered office: Mills House Mills Way, Boscombe Down Business Park, Amesbury, Wiltshire, England, SP4 7RX
