### ISSUE TITLE
Return 'isHaloConnected ' from Connect-HaloAPI?

### ISSUE THREAD

**Issue by sullymanmanmanamn** [homotechsual/HaloAPI#22]
Currently evaluating return via `-InformationVariable IsHaloConnected` and thinking it may be useful for it to be returned natively? 

`Connect-HaloAPI -ClientID $HaloConnectionParameters.ClientID 
    -ClientSecret $HaloConnectionParameters.ClientSecret 
    -Scopes $HaloConnectionParameters.Scopes 
    -Tenant $HaloConnectionParameters.Tenant 
    -URL $HaloConnectionParameters.URL 
    -InformationVariable IsHaloConnected
`

**Comment by homotechsual** [comment]
This is a good idea :-)
