### ISSUE TITLE
[Feature]: Asset Groups

### ISSUE THREAD

**Issue by JohnboyOnGithub** [homotechsual/HaloAPI#3]
### What happened?

Not a bug, but a useful feature would be to be able to pull the Asset types/Asset group information from Halo 

### Version

1.0.1

### Which operating systems have you tested on?

- [ ] Windows 10
- [ ] Windows 11
- [ ] Mac OS
- [ ] Linux

### Halo Product

Halo PSA

### Halo Version

n/a

**Comment by homotechsual** [comment]
This is on the roadmap - probably within the 1.3.x series :-)

**Comment by homotechsual** [comment]
1f5d70d0fd03f8e67f6c7d80e4b3213649a34bb9 fixes this.
