### ISSUE TITLE
[Bug]: Operation is not valid due to the current state of the object

### ISSUE THREAD

**Issue by daniel-kuhn-ict** [homotechsual/HaloAPI#32]
### Contact Details

dk@pkcg.com.au

### What happened?

While running warranty update into Halo, continually receive this error.
This throws the error against different devices, intermittently.

Line |
  65 |          throw $ErrorRecord.Exception.Message
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation is not valid due to the current state of the object.

### Version

1.0.1

### Which operating systems have you tested on?

- [ ] Windows 10
- [X] Windows 11
- [ ] Mac OS
- [ ] Linux

### What PowerShell version are you running?

None

### Halo Product

Halo PSA

### Halo Version

2.126.32

### What command did you run?

```PowerShell
Running warranty update using the HaloAPI via PSWarranty module.
Don't believe it is the module as this is running fine against DattoAPI.
```

**Comment by homotechsual** [comment]
This should have been resolved now - it was an issue in the background with Halo vs PowerShell 7.4.0
