### ISSUE TITLE
[Feature]: Add paymentstatuses paramtert to Get-HaloInvoice

### ISSUE THREAD

**Issue by xasz** [homotechsual/HaloAPI#33]
### Contact Details

discod xasz

### What happened?

There is no way to get unpaid invoices only.

### Version

1.0.1

### Which operating systems have you tested on?

- [ ] Windows 10
- [ ] Windows 11
- [ ] Mac OS
- [ ] Linux

### What PowerShell version are you running?

7.2.0-preview.8

### Halo Product

Halo PSA

### Halo Version

2.135.4

### What command did you run?

```PowerShell
This would be a valid HaloAPI request to show unpaid invoices

    api/Invoice?invoicedatestart=2023-01-04T07%3A55%3A24.050Z
    &invoicedateend=2024-01-04T23%3A00%3A00.000Z
    &paymentstatuses=0%2C-1
    &pageinate=true
    &page_size=50
    &page_no=1
    &includeinactive=undefined
    &includeinvoices=true
    &includecredits=false
    &includepoinvoices=false
    &order=invoice_date
    &orderdesc=true
    &order2=id
    &orderdesc2=true
```

### What was the output of the command?

```shell
None
```

**Comment by homotechsual** [comment]
Resolved with 1.18.0 - update your PowerShell version to the latest 7.3.x release - we generally **only** support the current stable PowerShell 7 - with the exception of 7.4.0 until Halo fix a bug.

**Comment by xasz** [comment]
thanks. my powershell version is up2date or at least on 7.39, but i cannot choose 7.39 in your bug report

**Comment by homotechsual** [comment]
7.3.10 is the latest - I'll have to check the form :-)

**Comment by homotechsual** [comment]
Fixed the bug report form - thanks!
