### ISSUE TITLE
[Bug]: Remove-HaloAsset is not exported.

### ISSUE THREAD

**Issue by jmv-support** [homotechsual/HaloAPI#38]
### Contact Details

leon.dejong@jmv-solutions.co.uk

### What happened?

A bug happened! Remove-HaloAsset doesn't work since it's not exported in the HaloAPI.psd1 All the code is there, it's just not exported.

### Version

1.20.0

### Which operating systems have you tested on?

- [ ] Windows 10
- [X] Windows 11
- [ ] Mac OS
- [ ] Linux

### What PowerShell version are you running?

7.4.1

### Halo Product

Halo PSA

### Halo Version

2.143.2

### What command did you run?

```PowerShell
Remove-HaloAsset -AssetID 6344
```

### What was the output of the command?

```shell
Remove-HaloAsset: The term 'Remove-HaloAsset' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by homotechsual** [comment]
Will get that fixed for a new release this week - thanks for pointing it out :-)
