### ISSUE TITLE
[Bug]: PowerShell 7.4 Support

### ISSUE THREAD

**Issue by FarazUSL** [homotechsual/HaloAPI#42]
### Contact Details

Faraz.Shaukat@upsher-smith.com

### What happened?

 incompatible with PowerShell 7.4.
 https://docs.homotechsual.dev/modules/haloapi/
 
 Not seeing an up date on support for the latest PowerShell 7 versions; and the page has had a message indicating Halo is looking at it.
 
 Is there something we do to help push Halo to solve the incompatibility with 7.4.x ?

### Version

1.20

### Which operating systems have you tested on?

- [X] Windows 10
- [X] Windows 11
- [ ] Mac OS
- [ ] Linux

### What PowerShell version are you running?

7.3.10.0

### Halo Product

Halo ISTM

### Halo Version

2.143.95

**Comment by homotechsual** [comment]
Hey Faraz, this should now be solved - we'll be dropping the note from the docs shortly.

**Comment by homotechsual** [comment]
Done
